# we need to disable this rule  issue related https://github.com/realm/SwiftLint/issues/3046 
disabled_rules:
  - vertical_parameter_alignment
  - unused_setter_value
  - notification_center_detachment
excluded:
  - Pods
vertical_whitespace:
  max_empty_lines: 1
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
function_body_length:
  warning: 100
  error: 150
type_body_length:
  warning: 300
  error: 500
opt_in_rules:
  indentation_width
identifier_name:
  excluded:
    - id
file_length:
  warning: 500
  error: 1200
